### ISSUE TITLE
Support WDL's Map type

### ISSUE THREAD

**Issue by TMiguelT** [dnanexus-rnd/dxWDL#23]
I just tried to run a workflow that used a [`Map`](https://github.com/broadinstitute/wdl/blob/develop/SPEC.md#map-literals), and it failed with this error:

```
Initial inputs=Map(gatk -> WdlVarLinks(WdlFileType,DxlJsValue({"$dnanexus_link":"file-F22gkvQ03kf0f3z88kY3gQQ1"})), genomeReference -> WdlVarLinks(WdlFileType,DxlJsValue({"$dnanexus_link":"file-B6qq93v2J35fB53gZ5G0007K"})), normalSamples -> WdlVarLinks(WdlMaybeEmptyArrayType(WdlFileType),DxlJsValue([{"$dnanexus_link":"file-F2005p803kf9XXPP8kkVG178"},{"$dnanexus_link":"file-F2005jj03kf9XXPP8kkVG176"}])), tumourSamples -> WdlVarLinks(WdlMaybeEmptyArrayType(WdlFileType),DxlJsValue([{"$dnanexus_link":"file-F2005j003kfP2fVB8kPpV3b6"},{"$dnanexus_link":"file-F2005fQ03kf21XX1P8pjqj3V"}])), genomeIndices -> WdlVarLinks(WdlMaybeEmptyArrayType(WdlFileType),DxlJsValue([{"$dnanexus_link":"file-ByGVY5j04Y0xPfZZfQ0Y85p6"},{"$dnanexus_link":"file-B6qq53v2J35Qyg04XxG0000V"}])))
java.lang.Exception: Unsupported WDL type Map[String, String] {"id": "tumour", "read1": "/home/dnanexus/execution/inputs/HG002_L1_R1.fastq.gz", "read2": "/home/dnanexus/execution/inputs/HG002_L1_R2.fastq.gz"}
	at dxWDL.WdlVarLinks$.jsOfComplexWdlValue(WdlVarLinks.scala:247)
	at dxWDL.WdlVarLinks$.$anonfun$jsOfComplexWdlValue$1(WdlVarLinks.scala:238)
	at dxWDL.WdlVarLinks$$$Lambda$180/1848289347.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$Lambda$26/1007309018.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at dxWDL.WdlVarLinks$.jsOfComplexWdlValue(WdlVarLinks.scala:238)
	at dxWDL.WdlVarLinks$.apply(WdlVarLinks.scala:261)
	at dxWDL.RunnerEval$.evalDecl$1(RunnerEval.scala:89)
	at dxWDL.RunnerEval$.$anonfun$evalDeclarations$3(RunnerEval.scala:99)
	at dxWDL.RunnerEval$$$Lambda$162/1297978429.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$Lambda$26/1007309018.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at dxWDL.RunnerEval$.evalDeclarations(RunnerEval.scala:98)
	at dxWDL.RunnerEval$.apply(RunnerEval.scala:129)
```

Hopefully the `Map` type should translate pretty easily to a JSON object.

**Comment by orodeh** [comment]
Michael,
   The problem is not JSON, the WDL map type is not supported yet in dxWDL. However, supporting it this week. I am plan to have it ready in the next release. 

   I hope that helps, 
        Ohad.

**Comment by orodeh** [comment]
@TMiguelT, I believe release 0.33 solves this problem.
