### ISSUE TITLE
File variables stored as Strings are lost when entering a scatter block

### ISSUE THREAD

**Issue by TMiguelT** [dnanexus-rnd/dxWDL#24]
Because of the way that dxWDL implements `Scatter` blocks (as a separate app from the `workflow` block), a filepath stored as a `String` will be passed into the scatter block as a `String`, and then try to be converted to a `File` when running the `task`, but at this point the file is not present. Consider this (simplified) WDL:

```scala
workflow mutect2 {
  Array[File] tumourSamples
  Array[File] normalSamples
  File genomeReference
  Array[File] genomeIndices

  # Array of sample data, in the format [id, read1, read2] (because dxWDL doesn't support Map[])
  Array[Array[String]] samples = [["tumour", tumourSamples[0], tumourSamples[1]], ["normal", normalSamples[0], normalSamples[1]]]

  scatter (sample in samples){
    call align {input: read1=sample[1], read2=sample[2], sampleName=sample[0], reference=genomeReference, referenceIndices=genomeIndices}
  }   
}

task align {
  File read1
  File read2
  String sampleName
  File reference
  Array[File] referenceIndices

  command {
    bwa mem ${reference} ${read1} ${read2} -R "@RG\tID:${sampleName}\tSM:${sampleName}" > ${sampleName}.bam
  }
  
  output{
    File bam = "${sampleName}.bam"
  }
}
```

This code compiles to two applets, the first of which succeeds, the second of which fails:
![image](https://user-images.githubusercontent.com/5019367/27774911-b6e18c04-5fde-11e7-930d-b1bfde98bb37.png)

This second applet failed with the following error:
```
envWithIterItem= Map(samples -> WdlVarLinks(WdlMaybeEmptyArrayType(WdlMaybeEmptyArrayType(WdlStringType)),DxlComplexValue([["tumour","/home/dnanexus/execution/inputs/HG002_L1_R1.fastq.gz","/home/dnanexus/execution/inputs/HG002_L1_R2.fastq.gz"],["normal","/home/dnanexus/execution/inputs/HG003_L1_R1.fastq.gz","/home/dnanexus/execution/inputs/HG003_L1_R2.fastq.gz"]],Vector())), genomeReference -> WdlVarLinks(WdlFileType,DxlJsValue({"$dnanexus_link":"file-B6qq93v2J35fB53gZ5G0007K"})), genomeIndices -> WdlVarLinks(WdlMaybeEmptyArrayType(WdlFileType),DxlJsValue([{"$dnanexus_link":"file-B6qq26v2J35bKZyfjZYQ0016"},{"$dnanexus_link":"file-B6qq53v2J35Qyg04XxG0000V"},{"$dnanexus_link":"file-B6qq6z42J35zJ6VJYbG0002f"},{"$dnanexus_link":"file-F2pJvF80Vzx54f69K4J8K5xy"},{"$dnanexus_link":"file-F2fYbF001473K5y08y11825F"},{"$dnanexus_link":"file-B6qqBkv2J35fB53gZ5G000Bv"}])), sample -> WdlVarLinks(WdlMaybeEmptyArrayType(WdlStringType),DxlComplexValue(["tumour","/home/dnanexus/execution/inputs/HG002_L1_R1.fastq.gz","/home/dnanexus/execution/inputs/HG002_L1_R2.fastq.gz"],Vector())))
dxWDL.AppInternalException: java.lang.RuntimeException: Output file /home/dnanexus/execution/inputs/HG002_L1_R1.fastq.gz is missing
	at dxWDL.Utils$.uploadFile(Utils.scala:454)
	at dxWDL.WdlVarLinks$.uploadFile$1(WdlVarLinks.scala:213)
	at dxWDL.WdlVarLinks$.jsOfComplexWdlValue(WdlVarLinks.scala:224)
	at dxWDL.WdlVarLinks$.apply(WdlVarLinks.scala:257)
	at dxWDL.RunnerEval$.evalDecl$1(RunnerEval.scala:89)
	at dxWDL.RunnerEval$.$anonfun$evalDeclarations$3(RunnerEval.scala:99)
	at dxWDL.RunnerEval$$$Lambda$187/253011924.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$Lambda$26/1007309018.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.immutable.List.map(List.scala:284)
	at dxWDL.RunnerEval$.evalDeclarations(RunnerEval.scala:98)
	at dxWDL.RunnerScatter$.$anonfun$evalScatter$1(RunnerScatter.scala:260)
	at dxWDL.RunnerScatter$.$anonfun$evalScatter$1$adapted(RunnerScatter.scala:254)
	at dxWDL.RunnerScatter$$$Lambda$195/1482246673.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at dxWDL.RunnerScatter$.evalScatter(RunnerScatter.scala:254)
	at dxWDL.RunnerScatter$.apply(RunnerScatter.scala:366)
	at dxWDL.Main$.appletAction(Main.scala:243)
	at dxWDL.Main$.dispatchCommand(Main.scala:275)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:327)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:14)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.App$$Lambda$5/2111991224.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at dxWDL.Main$.main(Main.scala:14)
	at dxWDL.Main.main(Main.scala)
Caused by: java.lang.RuntimeException: Output file /home/dnanexus/execution/inputs/HG002_L1_R1.fastq.gz is missing
	at dxWDL.AppInternalException.<init>(Utils.scala:26)
	... 39 more
failure running LaunchScatter
```

**Comment by orodeh** [comment]
The short answer, is that the strings need to be defined as Files, so that dxWDL will know to pass them as such. 

In this particular case, however, you had to use an `Array[Array[String]]` to get around a type limitation. If you don't want to wait for maps to be implemented, you can separate the structure into an `Array[String]`, and an `Array[Array[File]]`, like this:

```
Array[String] sampleNames= ["tumour", "normal"]
Array[Array[File]] sample = [[tumourSamples[0], tumourSamples[1]], [normalSamples[0], normalSamples[1]]]
```

Then, the iteration can be:

```
scatter (i in length(sampleNames)) {
     Array[String] row = sample[i]
     call align {input: read1=row[0], read2=row[1], sampleName=sampleNames[i], reference=genomeReference, referenceIndices=genomeIndices}
}
```

**Comment by TMiguelT** [comment]
Thanks, that's a nice workaround (although it should be `scatter (i in range(length(sampleNames)), I think`).

I suspect, because of this limitation (filepaths having to be `File`s, not `String`s), I won't be able to use `Map` even when it's implemented, because I need a mix of `String` and `File` types. So separate arrays may be how I do it (at least until WDL creates structs/strongly typed objects)

**Comment by orodeh** [comment]
@TMiguelT, can this issue be closed?

**Comment by TMiguelT** [comment]
I wonder if this should be documented somewhere, since it doesn't work the same as ordinary WDL.

**Comment by orodeh** [comment]
Agreed; this is surprising. I will document it in the readme file.

**Comment by orodeh** [comment]
This problem has been fixed on master branch through the use of type coercion.
