### ISSUE TITLE
Support WDL Pair type

### ISSUE THREAD

**Issue by TMiguelT** [dnanexus-rnd/dxWDL#25]
I'm sure you're aware of this, but it's not mentioned in the README, so I assumed Pairs would be usable in dxWDL. Instead they fail with this error:
```
tar: Removing leading `/' from member namesJul 3, 2017 12:00 PM
Initial inputs=Map(gatk -> WdlVarLinks(WdlFileType,DxlJsValue({"$dnanexus_link":"file-F22gkvQ03kf0f3z88kY3gQQ1"})), genomeReference -> WdlVarLinks(WdlFileType,DxlJsValue({"$dnanexus_link":"file-B6qq93v2J35fB53gZ5G0007K"})), normalSamples -> WdlVarLinks(WdlMaybeEmptyArrayType(WdlFileType),DxlJsValue([{"$dnanexus_link":"file-F2005p803kf9XXPP8kkVG178"},{"$dnanexus_link":"file-F2005jj03kf9XXPP8kkVG176"}])), tumourSamples -> WdlVarLinks(WdlMaybeEmptyArrayType(WdlFileType),DxlJsValue([{"$dnanexus_link":"file-F2005j003kfP2fVB8kPpV3b6"},{"$dnanexus_link":"file-F2005fQ03kf21XX1P8pjqj3V"}])), genomeIndices -> WdlVarLinks(WdlMaybeEmptyArrayType(WdlFileType),DxlJsValue([{"$dnanexus_link":"file-B6qq26v2J35bKZyfjZYQ0016"},{"$dnanexus_link":"file-B6qq53v2J35Qyg04XxG0000V"},{"$dnanexus_link":"file-B6qq6z42J35zJ6VJYbG0002f"},{"$dnanexus_link":"file-F2pJvF80Vzx54f69K4J8K5xy"},{"$dnanexus_link":"file-F2fYbF001473K5y08y11825F"},{"$dnanexus_link":"file-B6qqBkv2J35fB53gZ5G000Bv"}])))
java.lang.Exception: Unsupported WDL type Pair[String, Array[File]] ("tumour", ["/home/dnanexus/execution/inputs/HG002_L1_R1.fastq.gz", "/home/dnanexus/execution/inputs/HG002_L1_R2.fastq.gz"])
	at dxWDL.WdlVarLinks$.jsOfComplexWdlValue(WdlVarLinks.scala:247)
	at dxWDL.WdlVarLinks$.$anonfun$jsOfComplexWdlValue$1(WdlVarLinks.scala:238)
	at dxWDL.WdlVarLinks$$$Lambda$161/1902671237.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$Lambda$26/1007309018.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at dxWDL.WdlVarLinks$.jsOfComplexWdlValue(WdlVarLinks.scala:238)
	at dxWDL.WdlVarLinks$.apply(WdlVarLinks.scala:261)
	at dxWDL.RunnerEval$.evalDecl$1(RunnerEval.scala:89)
	at dxWDL.RunnerEval$.$anonfun$evalDeclarations$3(RunnerEval.scala:99)
	at dxWDL.RunnerEval$$$Lambda$154/691690486.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$Lambda$26/1007309018.apply(Unknown Source)
	at scala.collection.Iterator.foreach(Iterator.scala:929)
	at scala.collection.Iterator.foreach$(Iterator.scala:929)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1406)
	at scala.collection.IterableLike.foreach(IterableLike.scala:71)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at dxWDL.RunnerEval$.evalDeclarations(RunnerEval.scala:98)
	at dxWDL.RunnerEval$.apply(RunnerEval.scala:129)
	at dxWDL.Main$.appletAction(Main.scala:241)
	at dxWDL.Main$.dispatchCommand(Main.scala:274)
	at dxWDL.Main$.delayedEndpoint$dxWDL$Main$1(Main.scala:327)
	at dxWDL.Main$delayedInit$body.apply(Main.scala:14)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.App$$Lambda$5/2111991224.apply(Unknown Source)
	at scala.collection.immutable.List.foreach(List.scala:378)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at dxWDL.Main$.main(Main.scala:14)
	at dxWDL.Main.main(Main.scala)
failure running Eval
Close
```

**Comment by orodeh** [comment]
You are correct, the pair type will be supported in the next release. You can iterate on a map with a pair variable; hence, pairs are required for making maps usable.

**Comment by orodeh** [comment]
@TMiguelT, I believe release 0.33 solves this problem.
